### ISSUE TITLE
Stupid question - why use this rather than setting process.title

### ISSUE THREAD

**Issue by lanzkron** [daguej/node-windows-console-title#1]
Doesn't setting process.title achieve the same thing without additional dependencies?

**Comment by daguej** [comment]
To be honest, I never even looked at `process.title` since the [docs](https://nodejs.org/api/process.html#process_process_title) say it has different semantics: it's supposed to change the name of the process in the task manager (`ps`), and this is exactly what it does on *nix.  (Changing what appears in the GUI terminal emulator's titlebar involves an escape sequence, which is what [console-title](https://github.com/daguej/node-console-title) does.)

However, you can't really change the name of a process under Windows.  Task Manager displays the _image name_, so the only way to change what appears there it to rename the .exe file.

Since renaming the process can't happen on Windows, [libuv made the decision to have `uv_set_process_title` just call](https://github.com/libuv/libuv/blob/v1.9.0/src/win/util.c#L355-401) [`SetConsoleTitle`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686050%28v=vs.85%29.aspx), which is documented to "set the title for the current console window."  (This is semantically a different thing than changing the name of the process itself, so arguably libuv might [should?] change the behavior of `uv_set_process_title` on Windows.)

So to answer the question, yes, setting `process.title` **_on Windows**_ currently achieves the same outcome as this module.

console-title could be changed to ditch this dependency in favor of setting `process.title`, but I'm not sure whether that would be taking advantage of a side-effect type of functionality.
